//v174 Copyright (c) 2008-2021 33Across Inc. All Rights Reserved

Tynt=window.Tynt||[];
"undefined"==typeof Tynt.TIL&&"undefined"==typeof Tynt.TCL&&"undefined"==typeof Tynt.TICFL&&function(){var e=window,g=document,h={distro:"TC",id:"TC-"+(new Date).getTime()};Tynt.TCL=function(){function X(a,b,c){f.on(a,b,c)}function J(a){var b=J.options;a=b.parser[b.strictMode?"strict":"loose"].exec(a);for(var c={},d=14;d--;)c[b.key[d]]=a[d]||"";c[b.q.name]={};c[b.key[12]].replace(b.q.parser,function(a,d,e){d&&(c[b.q.name][d]=e)});return c}if(document.body){Date.now||(Date.now=function(){return(new Date).getTime()});
var f={_maxRef:600,_idMacro:"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",init:function(){this._icUrl=h.protocol+(Tynt.e||"")+"ic.tynt.com";this._debUrl=h.protocol+(Tynt.e||"")+"de.tynt.com/deb/v2";this._sicUrl=h.protocol+(Tynt.e||"")+"cdn-sic.33across.com/1/javascripts/sic.js";this._apUrl=h.protocol+(Tynt.e||"")+"cdn-ap.33across.com/javascripts/ap.js"},newEle:function(a,b,c,d){d=d||window;a=d.document.createElement(a);b&&this.extend(a,b);c&&this.extend(a.style,c);return a},injectScript:function(a,
b,c){b=b||window;a=this.newEle("script",{async:"async",referrerPolicy:"unsafe-url",type:"text/javascript",src:a},null,b);this.insertEle(a,c||b.document.getElementsByTagName("script")[0])},injectSicScript:function(a){this.injectScript(this._sicUrl,window,a)},injectApolloScript:function(){this.injectScript(this._apUrl)},injectSicIframe:function(a,b,c){var d={width:a.width+"px",height:a.height+"px",border:"0 none",margin:"0"};c&&this.extend(d,c);c=this.newEle("iframe",{referrerPolicy:"unsafe-url",src:"about:blank",
frameBorder:"0",frameSpacing:"0",scrolling:"no"},d);this.insertEle(c,b);a.iframeId=this.eleId(c);a.sicWindow=c.contentWindow;a=c.contentWindow.document;a.open();a.write('<!DOCTYPE html><html><head><style type="text/css">*{margin:0;padding:0;}</style></head><body><script type="text/javascript">window.Tynt = window.parent.Tynt;\x3c/script><script type="text/javascript" src="'+this._sicUrl+'">\x3c/script></body></html>');a.close()},insertEle:function(a,b){b?"script"==b.tagName.toLowerCase()?b.parentNode.insertBefore(a,
b):b.appendChild(a):document.body.appendChild(a)},eleId:function(a){var b=a.id;b||(b="x33x"+Date.now(),a.id=b);return b},_imgs:[],injectPixel:function(a,b,c){var d;try{d=g.createElement("img")}catch(q){d=document.createElement("img")}d&&(this._imgs.push(d),b&&(d.onload=b),c&&(d.onerror=c),d.referrerPolicy="unsafe-url",d.src=a)},docUrl:function(){var a=this.getLink("canonical");a||(a=this.getMeta("property","og:url","name","original-source"));if(a){if(0!=a.indexOf("http")){var b=h.protocol+e.location.host+
e.location.pathname,c=g.getElementsByTagName("base")[0];c&&(c=c.getAttribute("href"))&&(b=c);"/"==a.charAt(0)?(c=b.indexOf("/",9),-1<c&&(b=b.slice(0,c))):(c=b.lastIndexOf("/"),b=9<c?b.slice(0,c+1):b+"/");a=b+a}return a}return""},getMeta:function(a,b,c,d){var q,e=null,f=null,k=g.getElementsByTagName("meta");for(q=0;q<k.length;++q)e||k[q].getAttribute(a)!==b?c&&!f&&k[q].getAttribute(c)===d&&(f=k[q].getAttribute("content")||null):e=k[q].getAttribute("content")||null;return e||f},getLink:function(a,b){var c,
d,e=g.getElementsByTagName("link");for(c=0;c<e.length;++c)if(d=e[c].getAttribute("rel"),e[c].getAttribute("href")&&d&&(!b&&0<=d.indexOf(a)||b&&d==a))return e[c].href;return null},extend:function(a,b){var c,d;for(c=1;c<arguments.length;++c)for(d in arguments[c])arguments[c].hasOwnProperty(d)&&(a[d]=arguments[c][d]);return a},isArray:function(a){return"undefined"!=typeof a&&"[object Array]"===Object.prototype.toString.call(a)},inArray:function(a,b){return 0<=this.indexOf(a,b)},toArray:function(a,b){return Array.prototype.slice.call(a,
b||0)},indexOf:function(a,b){if(a.indexOf)return a.indexOf(b);for(var c=0;c<a.length;++c)if(a[c]===b)return c;return-1},unique:function(a){var b,c={},d=[];for(b=0;b<a.length;++b)c[a[b]]||(c[a[b]]=!0,d.push(a[b]));return d},iframeType:function(){var a=this.iframeEle(),b=K;if(a)b=a.id&&0<=a.id.search(/google_ads?_i?frame/)?6:L;else try{window!=window.top&&(b="undefined"!=typeof window.$sf?M:G)}catch(c){b=G,f.clog("iframeType: "+c.message)}return b},iframeEle:function(a){var b=null;a=a||window;try{b=
a.frameElement}catch(c){}return b},iframeTop:function(){var a=window,b=null;try{for(;a!=window.top;)b=a,a=a.parent}catch(c){return null}return b?this.iframeEle(b):null},getTopWin:function(){var a=window;try{for(;a.parent!==a&&a.parent.document;)a=a.parent}catch(b){}return a},isolated:function(){var a=!0;try{"function"==typeof window.top.open&&(a=!1)}catch(b){}return a},tyntIds:function(){return this.unique(Tynt).join("~")},getPubId:function(){for(var a=null,b=0;b<Tynt.length;++b)if("string"==typeof Tynt[b]&&
22==Tynt[b].length&&0>Tynt[b].indexOf("!")){a=Tynt[b];break}return a},countIds:function(a){var b,c=0;for(b=0;b<Tynt.length;++b)Tynt[b]===a&&++c;return c},_log:function(a){"undefined"==typeof Tynt.debug&&0<e.location.search.indexOf("__tcdebugmode=1")&&e.console&&e.console.log&&(Tynt.debug=!0);if(!0===Tynt.debug||1===Tynt.debug)a.unshift("[TC]"),e.console.log.apply(e.console,a)},log:function(){h.inXOIframe()?this.clog.apply(this,arguments):this._log(this.toArray(arguments))},clog:function(){var a=this.toArray(arguments);
a.unshift(h.id);this._log(a)},callIcU:function(){e._33Across.state.icDone=N;f.clog("Calling IC/U");this.injectPixel(this._icUrl+"/u",function(){e._33Across.state.icDone=x})},callIc:function(){var a,b,c,d,q,B,l,k;if(!e._33Across.state.icDone){e._33Across.state.icDone=N;b=this.getCookie(g.cookie,"tracertraffic");a=e.location.hash;a=/tynt=/.test(a)?a.match(/tynt=?([^?&$#]*)/)[1]:!1;d=c=this._icUrl+"/b/p?id="+this.tyntIds()+(b?"&et="+b:"")+(a?"&a="+a:"")+("string"==typeof Tynt.b?"&b="+Tynt.b:"")+"&lm="+
h.type+"&ts="+Date.now()+"&dn="+h.distro+"&iso="+(this.isolated()?"1":"0")+(null==p.uspString?"":"&us_privacy="+p.uspString);(a=this.getMeta("property","og:image:url","property","og:image"))&&(d+="&img="+encodeURIComponent(this.trunc(a,250)));q=d;(a=this.getMeta("property","og:title"))&&a!=g.title&&(q+="&ct="+encodeURIComponent(this.trunc(a,200)));B=q;g.referrer&&(a=this.trunc(g.referrer,this._maxRef),B+="&r="+encodeURIComponent(a));l=B;if(a=g.title||e.location.hostname)a=this.trim(this.trunc(a,200)),
l+="&t="+encodeURIComponent(a);k=l;if(a=this.docUrl())a=this.trunc(a,400),k+="&cu="+encodeURIComponent(a);b=k;if(a=this.getLink("amphtml",!0))a=this.trunc(a,250),b+="&ah="+encodeURIComponent(a);f.callIc.rsp=function(){e._33Across.state.icDone=x};f.clog("Calling IC");this.injectPixel(b,f.callIc.rsp,function(){f.injectPixel(k,f.callIc.rsp,function(){f.injectPixel(l,f.callIc.rsp,function(){f.injectPixel(B,f.callIc.rsp,function(){f.injectPixel(q,f.callIc.rsp,function(){f.injectPixel(d,f.callIc.rsp,function(){f.injectPixel(c,
f.callIc.rsp)})})})})})})}},callDeb:function(a,b,c){function d(a,b){f.clog("Calling DEB "+b+(a?"":" on IC timeout"));var c=encodeURIComponent(f.trunc(g.referrer,f._maxRef)),d=p.uspString&&4==p.uspString.length?"&us_privacy="+p.uspString:"";f.injectScript(f._debUrl+"?id="+f.tyntIds()+"&dn="+h.distro+"&cc="+b+"&r="+c+d,e)}"undefined"==typeof a&&(a=1);e._33Across.state.deDone>=a||(++e._33Across.state.deDone,1!==e._33Across.state.deDone&&!0!==c||this.when(function(){return e._33Across.state.icDone==x},
d,{timeout:300,timeoutCallback:d,callbackData:e._33Across.state.deDone},this),b&&0<b.length&&setTimeout(function(){f.callDeb(a,b,!0)},b.shift()))},callDebX:function(a,b){function c(a,c){f[b?"log":"clog"]("Calling DEBx "+c+(a?"":" on IC timeout"));var B=encodeURIComponent(f.trunc(g.referrer,f._maxRef)),l=p.uspString&&4==p.uspString.length?"&us_privacy="+p.uspString:"";f.injectScript(f._debUrl+"?m=xch&id="+f.tyntIds()+"&dn="+h.distro+"&cc="+c+"&r="+B+l,e)}a||(a=10);e._33Across.state.dxDone>=a||(++e._33Across.state.dxDone,
this.when(function(){return e._33Across.state.icDone==x},c,{timeout:300,timeoutCallback:c,callbackData:e._33Across.state.dxDone},this))},jsonDecode:function(a){if("function"!=typeof Array.prototype.toJSON)return JSON.stringify(a);var b=Array.prototype.toJSON;delete Array.prototype.toJSON;a=JSON.stringify(a);Array.prototype.toJSON=b;return a},getCookie:function(a,b){for(var c=b+"=",d=a.split(";"),e=0;e<d.length;e++){for(var f=d[e];" "==f.charAt(0);)f=f.substring(1,f.length);if(0==f.indexOf(c))return f.substring(c.length,
f.length)}return null},trim:function(a){return a.replace(/^\s+|\s+$/g,"")},trunc:function(a,b){var c,d;if(!a||a.length<=b)return a;c=a.substring(0,b);for(d=1;3>=d;++d)if("%"==c.charAt(c.length-d))return c.substring(0,c.length-d);return c},when:function(a,b,c,d){var f,g,l,k=null,O=null,m=a();c=c||{};f=c.interval||50;g=c.timeout;l=c.timeoutCallback||function(){};if(m)return b.call(d,m,c.callbackData),!0;k=e.setInterval(function(){if(m=a())e.clearInterval(k),e.clearTimeout(O),b.call(d,m,c.callbackData)},
f);g&&(O=e.setTimeout(function(){e.clearInterval(k);l.call(d,m,c.callbackData)},g));return!1},prob:function(a){a=parseFloat(a)||0;return Math.random()<a},on:function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,d||!1):a.attachEvent&&a.attachEvent("on"+b,c)},off:function(a,b,c,d){a.removeEventListener?a.removeEventListener(b,c,d||!1):a.detachEvent&&a.detachEvent("on"+b,c)}},p={uspString:null,init:function(){var a=this,b=function(){for(var a=window,b;!b;){try{a.frames.__uspapiLocator&&(b=a)}catch(c){}if(a===
window.top)break;a=a.parent}var d={};e.__uspapi=function(a,c,e){if(b){var f="usp-"+Math.random();a={__uspapiCall:{command:a,callId:f,version:c}};d[f]=e;b.postMessage(a,"*")}else e({msg:"__uspapi not found"},!1)};f.on(window,"message",function(a){var b=a.data;if("string"===typeof a.data)try{b=JSON.parse(a.data)}catch(c){}b.__uspapiReturn&&(a=b.__uspapiReturn,d[a.callId](a.returnValue,a.success),delete d[a.callId])},!1)},c=function(){e.__uspapi("getUSPData",1,function(b,c){c&&(a.uspString=b.uspString)})};
e.__uspapi||b();try{c()}catch(d){b(),c()}Tynt.getUspString=function(){return a.uspString};Tynt.getConsentString=function(){return null}}},N=1,x=2,K=0,G=3,M=4,L=5;h.type=0;h.inIframe=function(){return this.type>K};h.inSOIframe=function(){return this.type>=L&&6>=this.type};h.inXOIframe=function(){return this.type>=G&&this.type<=M};h.init=function(){this.type=f.iframeType();this.inSOIframe()&&(e=f.getTopWin(),g=e.document);e._33Across||(e._33Across={});e._33Across.state||(e._33Across.state={icDone:0,
deDone:0,dxDone:0,ivDone:!1});this.protocol="https://";f.init();p.init();this.isolated=f.isolated();f.clog("xoi="+this.inXOIframe()+", soi="+this.inSOIframe()+", iso="+this.isolated);e._33Across.pvTs||(e._33Across.pvTs=Date.now())};J.options={strictMode:!1,key:"source protocol authority userInfo user password host port relative path directory file query anchor".split(" "),q:{name:"queryKey",parser:/(?:^|&)([^&=]*)=?([^&]*)/g},parser:{strict:/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/,
loose:/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/}};h.init();var t=g.body,n=g.documentElement,Y=e.eval("/*@cc_on!@*/false"),P=function(a,b){for(var c="",d=0;d<b;d++)c+=a;return c},E=P("a",50),D=(Tynt.e||"")+"ic.tynt.com",Q=D+"/b/s",Z=function(a){"complete"==g.readyState?a():X(e,"load",function(b){setTimeout(function(){"undefined"!=typeof g.readyState||
Y||(g.readyState="complete");a()},10)})},y=function(a,b){var c=[],d=function(a,b){var c=h.protocol+a.replace("id="+E,"id="+f.tyntIds());-1<c.indexOf(D+"/b/p?")&&"string"==typeof Tynt.b&&(c+="&b="+Tynt.b);var d=new Image(1,1);b&&(d.onerror=b);d.src=c};y=function(a,b){c.push([a,b])};Z(function(){y=d;for(var a=0;a<c.length;a++)y(c[a][0],c[a][1]);c=null});y(a,b)},R=function(a){var b=[],c="",d;for(d in a)a.hasOwnProperty(d)&&(b.push(c,d,"=",a[d]),c="&");return b.join("")},T=function(a){for(var b=0,c=100>
a.length?a.length:100,d=0;d<c;d++)b+=a.charCodeAt(d);a=Math.floor(3844*Math.random());c=Math.abs(Date.now()-12281184E5);return S(c,7)+S((b+a)%3844,2)},U=function(a){if(62>a)return"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(this);var b=Math.floor(a/62);a-=62*b;return 62<=b?U(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a):"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a)},
S=function(a,b){var c=U(a);return P("0",b-c.length)+c},aa=f.trim((g.title||e.location.hostname).toString()).replace(new RegExp(e.location.hash,"g"),""),ba=function(){if(-1!==g.cookie.indexOf("tracertraffic=")&&(!g.referrer||-1==g.referrer.indexOf(e.location.host))){var a=e.location.hostname.split("."),b,c=2;do b="tracertraffic=0;path=/;domain=."+a.slice(a.length-c,a.length).join(".")+";expires=Thu, 01 Jan 1970 00:00:00 GMT",g.cookie=b,c++;while(-1==g.cookie.indexOf("tracertraffic=0")&&c<=a.length);
-1==g.cookie.indexOf("tracertraffic=0")&&(g.cookie="tracertraffic=0;path=/;expires=Thu, 01 Jan 1970 00:00:00 GMT")}},v=function(){var a=[];return function(b){for(var c=a.length-1;0<=c;c--)if(a[c]==b)return!1;a.unshift(b);3<a.length&&a.pop();return!0}},ca=v(),da=v(),ea=function(a){var b,c=function(a){e.removeEventListener("blur",c,!1);H(b);return!0};return function(a){b=a.target||a.srcElement;e.removeEventListener("blur",c,!1);"IMG"==b.nodeName&&"A"!=b.parentNode.nodeName&&(e.addEventListener("blur",
c,!1),setTimeout(function(){g.removeEventListener("blur",c,!1)},1E4));return!0}}(),V=function(a){H(a.target||a.srcElement,!0)},w,W=function(a){a=a.target||a.srcElement;w="IMG"==a.nodeName?a:null},I=function(a){var b=function(a){return"number"==typeof a.pageX?{x:a.pageX-(n.scrollLeft?n.scrollLeft:t.scrollLeft),y:a.pageY-(n.scrollTop?n.scrollTop:t.scrollTop)}:{x:a.clientX,y:a.clientY}},c=function(a){a=b(a);return 0>=a.x||0>=a.y||a.x>=t.clientWidth||a.y>=t.clientHeight},d=function(a){a=b(a);return 0>=
a.x||0>=a.y||a.x>=n.clientWidth||a.y>=n.clientHeight},e=function(a){return"#document"==a.target.nodeName},f=function(a){a=b(a);return 4>=a.x||4>=a.y||a.x>=n.clientWidth-4||a.y>=n.clientHeight-4},l=function(a){l=navigator.userAgent.match("MSIE")?g.compatMode&&-1!=g.compatMode.indexOf("CSS")?d:c:navigator.userAgent.match("Firefox")?e:f;l(a)};return function(a){w&&l(a)&&(H(w),w=null);return!0}}();Tynt.ci=function(){var a;return function(b,c){a=c||a;var d=Q+["?ci=",b,"&id=",E,"&g=",a,"&r=",encodeURIComponent(g.referrer),
"&ts=",Date.now()].join("");y(d)}}();Tynt.st=function(){var a;return function(b,c,d,f){a=d||a;b=[Q,"?",encodeURIComponent(b),"=",encodeURIComponent(c),"&id=",E,"&g=",a,"&r=",encodeURIComponent(g.referrer),"&href=",encodeURIComponent(e.location.href),"&ts=",Date.now()];c="";if(f){c=[];d="";for(var h in f)f.hasOwnProperty(h)&&(c.push(d,encodeURIComponent(h),"=",encodeURIComponent(f[h])),d="&");c="&"+c.join("")}y(b.join("")+c)}}();Tynt.c?v=function(){}:(Tynt.c=!0,Tynt.m=Tynt.m||[],Tynt.n=Tynt.n||[],
v=function(){var a=!0,b,c=function(b,c){var d;d=(d=f.trim(c))?d.split(/\s+/i).length:0;var e={id:E,wc:d,c:c,f:a?1:0,t:aa};f.extend(e,b);a=!1;d=e.trace_type;delete e.trace_type;var g=e.g;delete e.g;for(var m=[],u="id wc f w h t c".split(" "),C=0;C<u.length;C++){var p=u[C],n=e[p];n&&m.push([p,encodeURIComponent(n).replace(/\'/g,"%27")]);delete e[p]}for(var r in e)e.hasOwnProperty(r)&&(u=e[r])&&m.push([r,encodeURIComponent(u).replace(/\'/g,"%27")]);r=[];var C=2048-((h.protocol+D+"/a/t/x#?").length+(3+
g.length)+5),p=m.length,z=n=0,A=0,t,v,x,w,F=0;for(r[F]={g:g,tp:null};n<p&&35>r.length;)t=m[n][0],e=m[n][1],x=t.length+2,v=C-x-z,0<v?(u=e.substring(A,A+v),w=u.slice(-2).indexOf("%"),-1<w&&(u=e.substring(A,A+v-2+w),z+=w+2),z+=u.length+x,A+=u.length,r[F][t]=u):z=C,z>=C&&(r[++F]={g:g,p:F},z=0),A>=e.length&&(n++,A=0);r[0].tp=r.length;y(D+"/b/t/"+d+"?"+R(r[0]));for(g=1;g<r.length;g++)y(D+"/b/x/"+d+"?"+R(r[g]))};e.addEventListener?(navigator.userAgent.match(/Firefox\/2\b/)||t.addEventListener("copy",V,!1),
e.addEventListener("mousedown",W,!1),e.addEventListener("dragleave",I,!1),e.addEventListener("dragexit",I,!1),g.addEventListener("contextmenu",ea,!1)):(t.attachEvent("oncopy",V),g.getElementsByTagName("html")[0].attachEvent("ondragleave",I),t.attachEvent("onmousedown",W));ba();f.callIc();var d=[15E3,15E3,15E3,15E3];"function"===typeof Tynt.TIL?f.callDeb(3,d,!0):f.callDeb(5,d,!0);return function(a,d){if(!g.getElementById("tyntSh")){var l,k,h;d&&(g.selection&&g.selection.createRange?(k=g.selection.createRange(),
h=k.duplicate(),l=k.text):(k=e.getSelection(),h=0<k.rangeCount&&k.getRangeAt(0),l=k.toString()));var m=a.src;if(m&&!l&&da(m)){k={trace_type:3,g:T(m),w:a.width,h:a.height};for(h=0;h<Tynt.n.length;h++)Tynt.n[h](k,m);c(k,m)}else if(l&&f.trim(l).length&&"TEXTAREA"!=a.nodeName&&"INPUT"!=a.nodeName){m=ca(l);k={trace_type:1};m&&(b=T(l));k.g=b;for(var n=!0,p=0;p<Tynt.m.length;p++)n=n&&Tynt.m[p](k,l,h,m);m&&n&&c(k,l)}}}});if(!/tracer=test|tracer=no_tracing|disableTracer=/.test(e.location.href)&&!/disableTracer=y/.test(g.cookie))var H=
v()}else setTimeout(function(){Tynt.TCL()},50)};Tynt.TCL()}();
